apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki
  namespace: argocd
spec:
  destination:
    namespace: wiki
    server: https://kubernetes.default.svc
  source:
    path: apps/wiki
    repoURL: https://github.com/khaddict/homelab_cloud.git
    targetRevision: main
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml
  project: default
