app: homepage
namespace: homepage

deployment:
  replicas: 1

secret:
  name: homepage

service_account:
  name: homepage

config_map:
  name: homepage

cluster_role:
  name: homepage

cluster_role_binding:
  name: homepage

services:
  proxmox:
    password: <path:kv/data/kubernetes#homepage_proxmox_token>
  argocd:
    password: <path:kv/data/kubernetes#homepage_argocd_token>
  traefik:
    password: <path:kv/data/kubernetes#traefik_dashboard_secret>
