apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argocd
    repoURL: https://github.com/khaddict/homelab_cloud.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
