apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "{{ .Values.client }}-network-policy"
  namespace: "{{ .Values.namespace }}"
spec:
  endpointSelector:
    matchLabels:
      client: "{{ .Values.client }}"
  ingress:
  - fromEndpoints:
    - matchLabels:
        client: "{{ .Values.client }}"
  egress:
  - toEndpoints:
    - matchLabels:
        client: "{{ .Values.client }}"
  # DNS IP (CoreDNS)
  - toCIDR:
    - "169.254.25.10/32"
