apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: "{{ .Values.namespace }}"
  labels:
    client: "{{ .Values.client }}"
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    client: "{{ .Values.client }}"
