apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: "{{ .Values.namespace }}"
  labels:
    client: "{{ .Values.client }}"
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web
    client: "{{ .Values.client }}"
