apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: "{{ .Values.namespace }}"
  labels:
    client: "{{ .Values.client }}"
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
      client: "{{ .Values.client }}"
  template:
    metadata:
      labels:
        app: web
        client: "{{ .Values.client }}"
    spec:
      containers:
      - name: web
        image: "{{ .Values.web.image }}"
        ports:
        - containerPort: {{ .Values.web.port }}
