apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`khaddict.homelab.lan`)
      services:
        - name: {{ .Values.service.name }}
          port: 80
  tls:
    secretName: {{ .Values.service.name }}-cert-secret
