apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-project-client2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khaddict/homelab_cloud.git
    targetRevision: main
    path: apps/cilium-project
    helm:
      valueFiles:
        - client_values/client2.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: client2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
