apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
secrets:
  - name: {{ .Values.secret.name }}
