apiVersion: v1
kind: Secret
metadata:
  name: homepage-cert-secret
  namespace: homepage
type: kubernetes.io/tls
stringData:
  tls.crt: |
    <path:kv/data/easypki/application/homepage.homelab.lan#homepage.homelab.lan.cert.pem>
  tls.key: |
    <path:kv/data/easypki/application/homepage.homelab.lan#homepage.homelab.lan.key.pem>
