apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.service_account.name }}
