apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.homelab.lan`)
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: homepage-cert-secret
