apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app }}-cert-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    <path:kv/data/easypki/application/changedetection.homelab.lan#changedetection.homelab.lan.cert.pem>
  tls.key: |
    <path:kv/data/easypki/application/changedetection.homelab.lan#changedetection.homelab.lan.key.pem>
