apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql
  labels:
    app: postgresql
    chart: postgresql-6.5.0
    release: "release-name"
    heritage: "Helm"
type: Opaque
stringData:
  postgresql-password: <path:kv/data/kubernetes/#wiki_psql_secret>
