apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-wiki
  labels:
    helm.sh/chart: wiki-2.3.0
    app.kubernetes.io/name: wiki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
